### ISSUE TITLE
大佬梨涡出现这个错误是什么意思呢？

### ISSUE THREAD

**Issue by ghost** [iisams/Scripts#2]
梨涡签到领现金, 开始!
2020/11/26 21:25:11:330  <error>      [JS Console]: Exception {}, TypeError: undefined is not an object (evaluating 'lwbody.replace'),

**Comment by iisams** [comment]
是因为没有签到获取到body

**Comment by ghost** [comment]
解决了是分流规则拦截了，谢谢大佬。
