### ISSUE TITLE
梨涡可以获取CK，但是签到报错

### ISSUE THREAD

**Issue by tanmx** [iisams/Scripts#3]
如图，可以获取CK，但是签到报错
![photo_2020-12-15_08-32-59.jpg](https://i.loli.net/2020/12/15/ZX86jWacw3qU7sM.jpg)

**Comment by iisams** [comment]
这种情况我也有过，有时候重新获取又好了😂

**Comment by iisams** [comment]
有时间我再抓包分析一下

**Comment by tanmx** [comment]
> 有时间我再抓包分析一下

感谢大佬

**Comment by iisams** [comment]
解决了

**Comment by iisams** [comment]
> > 有时间我再抓包分析一下
> 
> 感谢大佬

更新了👌
