### ISSUE TITLE
反馈:tqz.js在loon可以用，最近转qx了发现脚本用不了

### ISSUE THREAD

**Issue by ZeroMah** [iisams/Scripts#6]
脚本运行后没有输出，进入京东查看签到也未完成，具体体现![image](https://user-images.githubusercontent.com/63148494/112734251-8fbbcc00-8f7f-11eb-9749-298f20589e77.png)
排除ck和网络问题
在loon上正常运行
梨涡下架后这个小白成长分也下架吗

**Comment by iisams** [comment]
好的，我试了我的QX是可以运行的，后面有时间再优化吧，（可能会懒癌发作哈）。特权活力值目前是继续运营的，还没有通知停止的消息。但铁定的是梨涡要倒了（再见，小羊毛）。

**Comment by iisams** [comment]
刚刚解决了 请放心食用
